# OmniRetail Customer Analytics
## 01 — Raw Data Inspection

### 1. Objective

The objective of this notebook is to understand the structure,
quality, and characteristics of the raw OmniRetail customer dataset
before performing any data-cleaning or analytical transformations.

In [3]:
import pandas as pd
import numpy as np

file_path = "../data/OmniRetail_Customer_Analytics_Group_Project.xlsx" 

df = pd.read_excel(file_path)

print("Shape of the dataset:", df.shape)
display(df.head())
display(df.tail())

Shape of the dataset: (5450, 22)

,Customer_ID,Snapshot_Date,Region,City_Tier,Age,Annual_Income_000,Annual_Spend_000,Store_Visits_Year,Online_Orders_Year,Avg_Basket_Value,...,Tenure_Months,Return_Rate_Pct,Satisfaction_Score,Complaints_Year,Loyalty_Points,Membership_Tier,Preferred_Category,Acquisition_Channel,Signup_Date,Last_Purchase_Date
0,C104801,2026-08-01 00:00:00,South,Tier 2,43.0,671.4,121.6,6,20,2480.1,...,61,10.8,6.1,3,1835,Silver,Home,Store Walk-in,2021-07-04 00:00:00,2026-07-18 00:00:00
1,C104444,2026-08-01 00:00:00,West,Tier 2,18.0,587.3,241.3,2,36,2498.6,...,35,11.8,8.7,1,3711,Basic,Electronics,Marketplace,2023-09-02 00:00:00,2026-07-23 00:00:00
2,C103868,2026-08-01 00:00:00,North,Tier 2,33.0,824.9,210.7,14,29,2341.3,...,31,7.7,7.8,2,3871,Basic,Sports,Search Ads,2024-01-02 00:00:00,2026-07-26 00:00:00
3,C101648,2026-08-01 00:00:00,West,Tier 2,23.0,1116.1,233.6,23,27,3554.9,...,10,4.8,7.8,3,3085,Basic,Electronics,Store Walk-in,2025-10-01 00:00:00,2026-07-29 00:00:00
4,C101693,2026-08-01 00:00:00,South,Tier 3,64.0,1226.5,458.0,29,4,4258.2,...,81,3.1,7.4,1,6932,Silver,Beauty,Referral,2019-11-04 00:00:00,2026-07-05 00:00:00

,Customer_ID,Snapshot_Date,Region,City_Tier,Age,Annual_Income_000,Annual_Spend_000,Store_Visits_Year,Online_Orders_Year,Avg_Basket_Value,...,Tenure_Months,Return_Rate_Pct,Satisfaction_Score,Complaints_Year,Loyalty_Points,Membership_Tier,Preferred_Category,Acquisition_Channel,Signup_Date,Last_Purchase_Date
5445,C101459,2026-08-01 00:00:00,South,Tier 1,39.0,1258.7,505.5,8,24,6061.3,...,81,4.1,8.8,0,5966,Silver,Home,Organic,2019-11-04 00:00:00,NaN
5446,C102125,2026-08-01 00:00:00,North,Tier 1,30.0,737.8,220.7,19,15,2323.4,...,30,8.7,7.2,1,3500,Basic,Sports,Store Walk-in,2024-02-01 00:00:00,2026-06-28 00:00:00
5447,C105048,2026-08-01 00:00:00,East,Tier 3,41.0,1953.3,689.9,16,28,8013.9,...,54,9.0,7.1,1,8637,Platinum,Home,Referral,2022-02-02 00:00:00,2026-06-27 00:00:00
5448,C100794,2026-08-01 00:00:00,North,Tier 2,35.0,1488.8,620.9,15,22,4294.1,...,87,6.3,9.1,0,7694,Platinum,Apparel,Store Walk-in,2019-05-06 00:00:00,2026-06-08 00:00:00
5449,C102305,2026-08-01 00:00:00,West,Tier 1,59.0,642.1,283.7,31,1,3680.9,...,106,2.3,9.1,3,4470,Silver,Apparel,Search Ads,2017-10-05 00:00:00,2026-07-08 00:00:00

In [4]:
df.info()
print(df.dtypes)
display(df.describe(include='all').T)

<class 'pandas.DataFrame'>
RangeIndex: 5450 entries, 0 to 5449
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Customer_ID          5450 non-null   str
 1   Snapshot_Date        5450 non-null   object
 2   Region               5402 non-null   str
 3   City_Tier            5450 non-null   str
 4   Age                  5378 non-null   float64
 5   Annual_Income_000    5330 non-null   float64
 6   Annual_Spend_000     5369 non-null   float64
 7   Store_Visits_Year    5450 non-null   int64
 8   Online_Orders_Year   5450 non-null   int64
 9   Avg_Basket_Value     5351 non-null   float64
 10  Online_Purchase_Pct  5388 non-null   float64
 11  Promo_Purchase_Pct   5373 non-null   float64
 12  Tenure_Months        5450 non-null   int64
 13  Return_Rate_Pct      5450 non-null   float64
 14  Satisfaction_Score   5337 non-null   float64
 15  Complaints_Year      5450 non-null   int64
 16  Loyalty_Points       5450 non-null   int64
 17  Membership_Tier      5395 non-null   str
 18  Preferred_Category   5408 non-null   str
 19  Acquisition_Channel  5450 non-null   str
 20  Signup_Date          5450 non-null   object
 21  Last_Purchase_Date   5382 non-null   object
dtypes: float64(8), int64(5), object(3), str(6)
memory usage: 936.8+ KB
Customer_ID                str
Snapshot_Date           object
Region                     str
City_Tier                  str
Age                    float64
Annual_Income_000      float64
Annual_Spend_000       float64
Store_Visits_Year        int64
Online_Orders_Year       int64
Avg_Basket_Value       float64
Online_Purchase_Pct    float64
Promo_Purchase_Pct     float64
Tenure_Months            int64
Return_Rate_Pct        float64
Satisfaction_Score     float64
Complaints_Year          int64
Loyalty_Points           int64
Membership_Tier            str
Preferred_Category         str
Acquisition_Channel        str
Signup_Date             object
Last_Purchase_Date      object
dtype: object

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Customer_ID,5450,5200,C101648,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Snapshot_Date,5450,3,2026-08-01 00:00:00,5433,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Region,5402,14,North,1515,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City_Tier,5450,11,Tier 1,2542,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,5378.0,NaN,NaN,NaN,39.223131,11.997072,12.0,30.0,38.0,48.0,110.0
Annual_Income_000,5330.0,NaN,NaN,NaN,1011.021501,469.760241,276.8,689.825,890.0,1216.55,9000.0
Annual_Spend_000,5369.0,NaN,NaN,NaN,302.389663,154.448046,-193.7,196.3,267.7,371.5,2500.0
Store_Visits_Year,5450.0,NaN,NaN,NaN,19.170092,14.819135,0.0,10.0,18.0,27.0,400.0
Online_Orders_Year,5450.0,NaN,NaN,NaN,17.356514,10.237287,0.0,9.0,17.0,25.0,48.0
Avg_Basket_Value,5351.0,NaN,NaN,NaN,3410.703027,1912.913924,-2082.8,2134.9,2875.7,4112.7,45000.0
Online_Purchase_Pct,5388.0,NaN,NaN,NaN,47.753953,23.131071,-12.0,30.5,47.35,64.5,132.0
Promo_Purchase_Pct,5373.0,NaN,NaN,NaN,37.168695,22.415137,-12.0,19.4,34.1,54.7,140.0
Tenure_Months,5450.0,NaN,NaN,NaN,56.521101,39.055494,-12.0,25.0,48.0,85.0,206.0
Return_Rate_Pct,5450.0,NaN,NaN,NaN,7.918862,5.348734,-4.0,4.6,7.6,10.9,130.0
Satisfaction_Score,5337.0,NaN,NaN,NaN,7.480326,1.104902,-2.0,6.7,7.5,8.2,15.0
Complaints_Year,5450.0,NaN,NaN,NaN,1.800734,1.817494,0.0,1.0,2.0,3.0,55.0
Loyalty_Points,5450.0,NaN,NaN,NaN,4545.161101,1908.80274,0.0,3028.0,4160.0,6097.75,10679.0
Membership_Tier,5395,13,Basic,2256,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Preferred_Category,5408,14,Electronics,945,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Acquisition_Channel,5450,13,Store Walk-in,1049,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Signup_Date,5450,187,2024-07-02 00:00:00,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Last_Purchase_Date,5382,117,2026-07-23 00:00:00,203,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Checking for missing values

In [5]:

missing = pd.DataFrame({
    "Missing Count": df.isna().sum(),
    "Missing Percentage": (df.isna().sum() / len(df)) * 100
})

display(
    missing.sort_values("Missing Percentage", ascending=False)
)

                     Missing Count  Missing Percentage
Annual_Income_000              120            2.201835
Satisfaction_Score             113            2.073394
Avg_Basket_Value                99            1.816514
Annual_Spend_000                81            1.486239
Promo_Purchase_Pct              77            1.412844
Age                             72            1.321101
Last_Purchase_Date              68            1.247706
Online_Purchase_Pct             62            1.137615
Membership_Tier                 55            1.009174
Region                          48            0.880734
Preferred_Category              42            0.770642
City_Tier                        0            0.000000
Customer_ID                      0            0.000000
Snapshot_Date                    0            0.000000
Return_Rate_Pct                  0            0.000000
Tenure_Months                    0            0.000000
Store_Visits_Year                0            0.000000
Online_Orders_Year               0            0.000000
Loyalty_Points                   0            0.000000
Complaints_Year                  0            0.000000
Acquisition_Channel              0            0.000000
Signup_Date                      0            0.000000

## Checking the catergorical columns and their unique values

In [6]:

categorical_cols = ["Region", "City_Tier", "Membership_Tier", "Preferred_Category","Acquisition_Channel"]

for col in categorical_cols:
    print("\n===========", col , "===========")
    print(df[col].value_counts(dropna=False))

for col in categorical_cols:
    print("\n", col)
    for value in df[col].dropna().unique():
        print(repr(value))

=========== Region ===========
Region
North     1515
South     1437
West      1293
East      1113
NaN         48
West         5
SOUTH        5
WEST         5
NORTH        5
eest         4
South        4
south        4
north        4
East         4
Nort         4
Name: count, dtype: int64

=========== City_Tier ===========
City_Tier
Tier 1    2542
Tier 2    2004
Tier 3     870
Tier-2       5
T2           5
T1           4
Tier1        4
Tier3        4
tier3        4
tier 1       4
TIER 2       4
Name: count, dtype: int64

=========== Membership_Tier ===========
Membership_Tier
Basic        2256
Silver       1824
Gold          921
Platinum      354
NaN            55
Platinum        5
Glod            5
basic           5
platinium       5
silver          4
BASIC           4
GOLD            4
SILVER          4
gold            4
Name: count, dtype: int64

=========== Preferred_Category ===========
Preferred_Category
Electronics    945
Beauty         918
Grocery        883
Sports         882
Home           880
Apparel        866
NaN             42
Grocerry         5
electronics      5
apparel          4
APPAREL          4
sports           4
Electroncs       4
BEAUTY           4
Home             4
Name: count, dtype: int64

=========== Acquisition_Channel ===========
Acquisition_Channel
Store Walk-in    1049
Organic          1046
Search Ads        972
Social Media      947
Referral          741
Marketplace       666
Referrral           5
market place        4
ORGANIC             4
Store Walkin        4
SocialMedia         4
social media        4
Search ads          4
Name: count, dtype: int64

 Region
'South'
'West'
'North'
'West '
'East'
'eest'
'SOUTH'
'WEST'
'South '
'south'
'north'
'East  '
'NORTH '
'Nort'

 City_Tier
'Tier 2'
'Tier 3'
'Tier 1'
'T1'
'Tier-2'
'Tier1'
'Tier3 '
'tier3'
'tier 1'
'T2'
'TIER 2'

 Membership_Tier
'Silver'
'Basic'
'Gold'
'Platinum'
'Platinum '
'silver '
'Glod'
'BASIC '
'basic'
'GOLD '
'SILVER'
'gold'
'platinium'

 Preferred_Category
'Home'
'Electronics'
'Sports'
'Beauty'
'Apparel'
'Grocery'
'apparel '
'Grocerry'
'APPAREL'
'sports '
'electronics'
'Electroncs'
'BEAUTY'
'Home '

 Acquisition_Channel
'Store Walk-in'
'Marketplace'
'Search Ads'
'Referral'
'Social Media'
'Organic'
'market place'
'Referrral'
'ORGANIC'
'Store Walkin'
'SocialMedia'
'social media'
'Search ads '

## Checking for duplicate customer IDs

In [7]:

print("Total rows:", len(df))
print("Unique customers:", df['Customer_ID'].nunique())
print(
    "Duplicate customer rows:", df["Customer_ID"].duplicated(keep=False).sum()
)

duplicate_counts = df["Customer_ID"].value_counts()

display(
    duplicate_counts[duplicate_counts > 1].sort_values(ascending=False)
)

Total rows: 5450
Unique customers: 5200
Duplicate customer rows: 500

Customer_ID
C101648    2
C101468    2
C102680    2
C100217    2
C102398    2
          ..
C104551    2
C103055    2
C100053    2
C104672    2
C101397    2
Name: count, Length: 250, dtype: int64

The data definetely has duplicate customer IDs but we need to also check that whether these rows have only customer ID as same or the whole row is identical. Identical rows can be dropped easily, but, with rows with different non-ID fields that are different have some value to them

In [8]:
duplicate_ids = duplicate_counts[
    duplicate_counts > 1
]

duplicate_rows = df[
    df["Customer_ID"].isin(duplicate_ids.index)
].sort_values("Customer_ID")

duplicate_summary = (
    duplicate_rows
    .groupby("Customer_ID")
    .agg(
        Rows=("Customer_ID", "size"),
        Distinct_Values=("Customer_ID", "nunique")
    )
)

duplicate_columns = [
    col for col in df.columns
    if col != "Customer_ID"
]

duplicate_comparison = (
    duplicate_rows
    .groupby("Customer_ID")[duplicate_columns]
    .nunique(dropna=False)
)

print("Duplicate customer IDs:", len(duplicate_comparison))

print(
    "IDs with completely identical non-ID fields:",
    (duplicate_comparison.max(axis=1) == 1).sum()
)

print(
    "IDs with at least one differing field:",
    (duplicate_comparison.max(axis=1) > 1).sum()
)

Duplicate customer IDs: 250
IDs with completely identical non-ID fields: 150
IDs with at least one differing field: 100

### Duplicate Customer Finding

The dataset contains 250 Customer_IDs that occur more than once.

Of these:
- 150 Customer_IDs (60%) have completely identical non-ID fields.
- 100 Customer_IDs (40%) have at least one differing field.

The 150 identical duplicates appear to be repeated copies of the
same customer records. The 100 conflicting duplicates require
further investigation before deciding how they should be treated.

In [9]:
conflicting_ids = duplicate_comparison[
    duplicate_comparison.max(axis=1) > 1
].index

conflicting_rows = duplicate_rows[
    duplicate_rows["Customer_ID"].isin(conflicting_ids)
].sort_values("Customer_ID")

difference_summary = {}

for col in duplicate_columns:
    difference_summary[col] = (
        duplicate_comparison.loc[conflicting_ids, col] > 1
    ).sum()

difference_summary = (
    pd.Series(difference_summary)
    .sort_values(ascending=False)
)

display(difference_summary)

Annual_Spend_000       99
Satisfaction_Score     89
City_Tier               0
Region                  0
Snapshot_Date           0
Annual_Income_000       0
Age                     0
Online_Orders_Year      0
Store_Visits_Year       0
Online_Purchase_Pct     0
Promo_Purchase_Pct      0
Tenure_Months           0
Avg_Basket_Value        0
Return_Rate_Pct         0
Complaints_Year         0
Loyalty_Points          0
Membership_Tier         0
Preferred_Category      0
Acquisition_Channel     0
Signup_Date             0
Last_Purchase_Date      0
dtype: int64

In [10]:
sample_conflicting_ids = (
    pd.Series(conflicting_ids)
    .sample(5, random_state=42)
    .tolist()
)

display(
    conflicting_rows[
        conflicting_rows["Customer_ID"].isin(sample_conflicting_ids)
    ]
)

,Customer_ID,Snapshot_Date,Region,City_Tier,Age,Annual_Income_000,Annual_Spend_000,Store_Visits_Year,Online_Orders_Year,Avg_Basket_Value,...,Tenure_Months,Return_Rate_Pct,Satisfaction_Score,Complaints_Year,Loyalty_Points,Membership_Tier,Preferred_Category,Acquisition_Channel,Signup_Date,Last_Purchase_Date
487,C102726,2026-08-01 00:00:00,West,Tier 1,26.0,862.9,232.3,24,20,2562.8,...,29,14.4,6.9,4,442,Basic,Beauty,Social Media,2024-03-03 00:00:00,2026-07-23 00:00:00
4416,C102726,2026-08-01 00:00:00,West,Tier 1,26.0,862.9,234.3,24,20,2562.8,...,29,14.4,7.0,4,442,Basic,Beauty,Social Media,2024-03-03 00:00:00,2026-07-23 00:00:00
2809,C102797,2026-08-01 00:00:00,East,Tier 1,23.0,903.2,271.9,4,26,2658.6,...,24,8.2,7.9,1,3272,Basic,Electronics,Referral,2024-08-02 00:00:00,2026-07-24 00:00:00
3178,C102797,2026-08-01 00:00:00,East,Tier 1,23.0,903.2,258.7,4,26,2658.6,...,24,8.2,7.3,1,3272,Basic,Electronics,Referral,2024-08-02 00:00:00,2026-07-24 00:00:00
2617,C103218,2026-08-01 00:00:00,South,Tier 1,30.0,704.0,196.0,11,26,1952.4,...,20,7.1,6.6,3,2277,Basic,electronics,Store Walk-in,2024-12-01 00:00:00,2026-06-18 00:00:00
1696,C103218,2026-08-01 00:00:00,South,Tier 1,30.0,704.0,193.7,11,26,1952.4,...,20,7.1,7.0,3,2277,Basic,electronics,Store Walk-in,2024-12-01 00:00:00,2026-06-18 00:00:00
2928,C103943,2026-08-01 00:00:00,North,Tier 2,37.0,779.4,220.2,14,38,2311.0,...,25,11.2,6.4,2,2717,Basic,Sports,Marketplace,2024-07-02 00:00:00,2026-07-01 00:00:00
1000,C103943,2026-08-01 00:00:00,North,Tier 2,37.0,779.4,226.8,14,38,2311.0,...,25,11.2,6.7,2,2717,Basic,Sports,Marketplace,2024-07-02 00:00:00,2026-07-01 00:00:00
564,C104399,2026-08-01 00:00:00,East,Tier 1,58.0,1567.8,478.1,24,24,4635.4,...,66,8.2,9.4,0,7961,Gold,Grocery,Marketplace,2021-02-02 00:00:00,2026-07-15 00:00:00
2768,C104399,2026-08-01 00:00:00,East,Tier 1,58.0,1567.8,484.4,24,24,4635.4,...,66,8.2,9.4,0,7961,Gold,Grocery,Marketplace,2021-02-02 00:00:00,2026-07-15 00:00:00

### Duplicate Variation Finding

Among the 100 Customer_IDs with differing duplicate records, the
variation is concentrated in two variables:

- `Annual_Spend_000` differs for 99 of the 100 duplicated customers.
- `Satisfaction_Score` differs for 89 of the 100 duplicated customers.

All other inspected variables, including demographic, geographic,
membership, behavioral, and date fields, are identical across the
duplicate records.

This suggests that the repeated records may represent duplicated
customer observations with altered spend and satisfaction values.
The records will therefore be investigated further before any
deduplication decision is made.

In [11]:
comparison_stats = (
    conflicting_rows
    .groupby("Customer_ID")
    .agg(
        Spend_Min=("Annual_Spend_000", "min"),
        Spend_Max=("Annual_Spend_000", "max"),
        Satisfaction_Min=("Satisfaction_Score", "min"),
        Satisfaction_Max=("Satisfaction_Score", "max")
    )
)

comparison_stats["Spend_Difference"] = (
    comparison_stats["Spend_Max"]
    - comparison_stats["Spend_Min"]
)

comparison_stats["Satisfaction_Difference"] = (
    comparison_stats["Satisfaction_Max"]
    - comparison_stats["Satisfaction_Min"]
)

display(comparison_stats.describe())

sample_conflicting_ids = (
    pd.Series(conflicting_ids)
    .sample(5, random_state=42)
    .tolist()
)

sample_duplicates = conflicting_rows[
    conflicting_rows["Customer_ID"].isin(sample_conflicting_ids)
].sort_values("Customer_ID")

display(
    sample_duplicates[
        [
            "Customer_ID",
            "Annual_Spend_000",
            "Satisfaction_Score"
        ]
    ]
)

,Spend_Min,Spend_Max,Satisfaction_Min,Satisfaction_Max,Spend_Difference,Satisfaction_Difference
count,100.000000,100.000000,95.000000,95.000000,100.000000,95.000000
mean,283.173000,291.351000,7.425263,7.712632,8.178000,0.287368
std,135.559328,138.597665,0.960271,0.967695,6.748941,0.205376
min,105.700000,110.000000,5.000000,5.600000,0.000000,0.000000
25%,198.125000,202.150000,6.700000,7.000000,3.550000,0.100000
50%,243.650000,249.100000,7.300000,7.700000,6.450000,0.200000
75%,318.525000,323.875000,8.050000,8.300000,10.825000,0.400000
max,714.400000,754.800000,10.000000,10.400000,42.100000,0.900000

     Customer_ID  Annual_Spend_000  Satisfaction_Score
487      C102726             232.3                 6.9
4416     C102726             234.3                 7.0
2809     C102797             271.9                 7.9
3178     C102797             258.7                 7.3
2617     C103218             196.0                 6.6
1696     C103218             193.7                 7.0
2928     C103943             220.2                 6.4
1000     C103943             226.8                 6.7
564      C104399             478.1                 9.4
2768     C104399             484.4                 9.4

### Conflicting Duplicate Inspection

Inspection of sample records shows that the 100 conflicting
Customer_IDs have identical values across all fields except
`Annual_Spend_000` and, in most cases, `Satisfaction_Score`.

The differences observed in the sample are generally relatively small,
but the repeated records cannot be treated as exact duplicates because
their customer-level values are not identical.

These records are therefore flagged for explicit treatment during the
cleaning stage rather than being removed automatically.

## Analysing the distribution of numerical columns

In [12]:

numeric_cols = [
    "Age",
    "Annual_Income_000",
    "Annual_Spend_000",
    "Store_Visits_Year",
    "Online_Orders_Year",
    "Avg_Basket_Value",
    "Online_Purchase_Pct",
    "Promo_Purchase_Pct",
    "Tenure_Months",
    "Return_Rate_Pct",
    "Satisfaction_Score",
    "Complaints_Year",
    "Loyalty_Points"
]

for col in numeric_cols:
    print(
        f"{col:25}"
        f"min={df[col].min():.2f}"
        f" max={df[col].max():.2f}"
    )

Age                      min=12.00 max=110.00
Annual_Income_000        min=276.80 max=9000.00
Annual_Spend_000         min=-193.70 max=2500.00
Store_Visits_Year        min=0.00 max=400.00
Online_Orders_Year       min=0.00 max=48.00
Avg_Basket_Value         min=-2082.80 max=45000.00
Online_Purchase_Pct      min=-12.00 max=132.00
Promo_Purchase_Pct       min=-12.00 max=140.00
Tenure_Months            min=-12.00 max=206.00
Return_Rate_Pct          min=-4.00 max=130.00
Satisfaction_Score       min=-2.00 max=15.00
Complaints_Year          min=0.00 max=55.00
Loyalty_Points           min=0.00 max=10679.00

## Inspecting the dates columns

In [13]:

date_cols = ["Snapshot_Date", "Last_Purchase_Date", "Signup_Date"]

for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')

for col in date_cols:
    print("\n", col)
    print("Min:", df[col].min())
    print("Max:", df[col].max())
    print("Missing:", df[col].isna().sum())
    print("Unique:", df[col].nunique())

display(df[date_cols].head(10))

#checking for failed conversions if any
for col in date_cols:
    print(
        col,
        "invalid/unparseable dates:",
        df[col].isna().sum()
    )

#checking for impossible dates (last purchase date before signup date)
print(
    "Signup after snapshot:",
    (df["Signup_Date"] > df["Snapshot_Date"]).sum()
)

print(
    "Last purchase after snapshot:",
    (df["Last_Purchase_Date"] > df["Snapshot_Date"]).sum()
)

print(
    "Last purchase before signup:",
    (df["Last_Purchase_Date"] < df["Signup_Date"]).sum()
)

 Snapshot_Date
Min: 2026-08-01 00:00:00
Max: 2026-08-01 00:00:00
Missing: 0
Unique: 1

 Last_Purchase_Date
Min: 2026-03-21 00:00:00
Max: 2026-08-01 00:00:00
Missing: 77
Unique: 97

 Signup_Date
Min: 2009-06-09 00:00:00
Max: 2026-07-02 00:00:00
Missing: 0
Unique: 174

  Snapshot_Date Last_Purchase_Date Signup_Date
0    2026-08-01         2026-07-18  2021-07-04
1    2026-08-01         2026-07-23  2023-09-02
2    2026-08-01         2026-07-26  2024-01-02
3    2026-08-01         2026-07-29  2025-10-01
4    2026-08-01         2026-07-05  2019-11-04
5    2026-08-01         2026-07-09  2017-06-05
6    2026-08-01         2026-06-04  2024-03-03
7    2026-08-01         2026-07-18  2023-01-02
8    2026-08-01         2026-06-23  2026-04-02
9    2026-08-01         2026-07-18  2024-07-02

Snapshot_Date invalid/unparseable dates: 0
Last_Purchase_Date invalid/unparseable dates: 77
Signup_Date invalid/unparseable dates: 0
Signup after snapshot: 0
Last purchase after snapshot: 0
Last purchase before signup: 4

checking the 4 problematic customer IDs with impossible dates

In [14]:

invalid_date_row = df[(df["Last_Purchase_Date"] < df["Signup_Date"])]

display(invalid_date_row[["Customer_ID", "Signup_Date", "Last_Purchase_Date", "Membership_Tier"]])

     Customer_ID Signup_Date Last_Purchase_Date Membership_Tier
1615     C100548  2026-07-02         2026-06-14           Basic
2019     C103972  2026-07-02         2026-06-27           Basic
3998     C102098  2026-07-02         2026-06-14           Basic
4041     C104187  2026-07-02         2026-06-26           Basic

## 10. Raw Data Quality Summary

The raw OmniRetail dataset contains 5,450 observations and 22
variables representing customer demographics, purchasing behavior,
loyalty, satisfaction, and customer relationship information.

The initial inspection identified several data-quality issues,
including missing values, duplicated Customer_IDs, inconsistent
categorical values, potentially invalid numerical values, and four
records where the last purchase date precedes the signup date.

These issues will be addressed systematically in the data-cleaning
stage. No modifications have been made to the original dataset in
this notebook.